// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

void moveMouseBase({required int x, required int y, required int coordinate}) =>
    RustLib.instance.api.crateApiBixatKeyMouseMoveMouseBase(
      x: x,
      y: y,
      coordinate: coordinate,
    );

void pressMouseButtonBase({required int button, required int direction}) =>
    RustLib.instance.api.crateApiBixatKeyMousePressMouseButtonBase(
      button: button,
      direction: direction,
    );

void enterTextBase({required String text}) =>
    RustLib.instance.api.crateApiBixatKeyMouseEnterTextBase(text: text);

void simulateKeyBase({required int key, required int direction}) => RustLib
    .instance
    .api
    .crateApiBixatKeyMouseSimulateKeyBase(key: key, direction: direction);

void simulateKeyCombinationBase({
  required List<int> keys,
  required BigInt durationMs,
}) => RustLib.instance.api.crateApiBixatKeyMouseSimulateKeyCombinationBase(
  keys: keys,
  durationMs: durationMs,
);

void scrollMouseBase({required int distance, required int axis}) => RustLib
    .instance
    .api
    .crateApiBixatKeyMouseScrollMouseBase(distance: distance, axis: axis);
